---
# Source: kubescape-operator/templates/configs/cloud-secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: cloud-secret
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: cloud-secret
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: cloud-secret
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    kubescape.io/infra: credentials
type: Opaque
data:
  account: ""
  accessKey: ""
