---
# Source: kubescape-operator/templates/configs/cloudapi-configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ks-cloud-config
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: ks-cloud-config
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: ks-cloud-config
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
    kubescape.io/infra: config
data:
  clusterData: |
    {
      "serviceDiscovery": false,
      "vulnScanURL": "kubevuln:8080",
      "kubevulnURL": "kubevuln:8080",
      "kubescapeURL": "kubescape:8080",
      "clusterName": "cluster",
      "storage": true,
      "relevantImageVulnerabilitiesEnabled": true,
      "namespace": "kubescape",
      "imageVulnerabilitiesScanningEnabled": true,
      "postureScanEnabled": true,
      "otelCollector": false,
      "nodeAgent": "true",
      "maxImageSize": 5.36870912e+09,
      "maxSBOMSize": 2.097152e+07,
      "keepLocal": true,
      "scanTimeout": "5m",
      "scanEmbeddedSBOMs": true,
      "vexGeneration": false,
      "useDefaultMatchers": false,
      "storeFilteredSbom": false,
      "continuousPostureScan": true,
      "relevantImageVulnerabilitiesConfiguration": "enable"
    }
