---
# Source: kubescape-operator/templates/configs/priority-class.yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubescape-critical
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: kubescape-critical
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: kubescape-critical
    tier: ks-control-plane
    kubescape.io/ignore: "true"
value: 1.000001e+08
globalDefault: false
description: "This priority class is for node-agent daemonset pods"
