---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-10.4.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "12.3.1"
    app.kubernetes.io/component: admin-secret
type: Opaque
data:
  
  admin-user: "YWRtaW4="
  admin-password: "MWRvTFFvZ0tQbGN1cFhUb0xTRG90T2JRcWhuYlZIcUJLRXlLYWF5Nw=="
  ldap-toml: ""
