---
# Source: kubescape-operator/templates/storage/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: "v1beta1.spdx.softwarecomposition.kubescape.io"
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  group: "spdx.softwarecomposition.kubescape.io"
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: "v1beta1"
  service:
    name: storage
    namespace: kubescape
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lRZm8wTzlZS0RCRWxXVHh2M1FnR3dLVEFOQmdrcWhraUc5dzBCQVFzRkFEQWcKTVI0d0hBWURWUVFERXhWemRHOXlZV2RsTFVjek4yeHRZMkpyVkZRdFkyRXdIaGNOTWpVeE1qSTVNVGt6T1RJeQpXaGNOTWpjeE1qSTVNVGt6T1RJeVdqQWdNUjR3SEFZRFZRUURFeFZ6ZEc5eVlXZGxMVWN6TjJ4dFkySnJWRlF0ClkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDeGZSZVB5SFVxTy9qQndnVncKUXU2YmN6UkQrM3hGRFN4K09TVnlaSHZxbFpOYkYvREd5RXpUKzZab05jaGFwbWQ4d1NYZ0lLR29NVGEvRDF5VgpnNEFsNkN4WGJGMlp6S1N4OG5Lc0pKR2krZUpvTkdBOG1KQzFEY1pVcUVZck9QNWsxaU1leFRaUzJubVpFdis1ClFLbUw0OFMyMmhPdVRNbmZVcW5VcGExNnFORU54MDRNRjBoajAybzBkeDNWTDdUNGl6eEVLVnozUFZ2eVpjcmUKR0V0d1I1WTU1RDh1YzJPbU1pQXVYTEdrUlQrbXVlSUI4cVpnTWptMXh2OTIweS9MUzhLSHA5c2xrS0tPVHBWSQpPQ0RGNE5BME9ZeTNOS1RNYlp0MXlQQmVNakZSOFFWY0J6dmR2K2VvVEJETGdSVDQ4dkRHWnBGNXBMMVJCOFZlClZjZ2xBZ01CQUFHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0QKQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRwa09vN0FZK1pFbQpPYnQ4ZGlSSk5hRW0xQnd3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVxbW1YUzRBdjd3bHg4TUJzcjg2UUlYCjFuY1l1VVZHTVJNVkI4OGZRWmdMUXV4Nll0R2JPMGczSzh2TmxPQnA0MXZ0cnp2L3dxV0Q1VjNLajhnRU9qWHUKL1VhRXlubEdKcDNuN3M3SGNGemphQUFTOUNYaHNSdEJnWXJSV0pJMmc2TnMxTlJxWUpxR2I4YVdKWWoyRnpuZgp6eWVJa043RGlQVzZvVnd4U2ZvTFNRbDlKaHRBaEFOb2JLditwcmNyZjFmblhSeFYvS1d3TzB5YVNMSUFRVmwyCk4yVU9TMG5LNUxTOS9LbGNNZ2kwNXNmQlV3Q0Q4alRzajMyRjJWM0JPbXBNMFVvSGM4anZ2VjFaZVVrbzJPVmcKYTdSRy9wNFNhWnhpM1BOemdWRjdsRHpCRFlJbEZISFFJS2c5d3lWQXFwanRlcG5VeHpZSExlMWRkaktpMm93PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
