---
# Source: kubescape-operator/templates/storage/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: "v1beta1.spdx.softwarecomposition.kubescape.io"
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  group: "spdx.softwarecomposition.kubescape.io"
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: "v1beta1"
  service:
    name: storage
    namespace: kubescape
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lRSzRZZ082N2FGbDNKNmpIcHNHdzQ1ekFOQmdrcWhraUc5dzBCQVFzRkFEQWcKTVI0d0hBWURWUVFERXhWemRHOXlZV2RsTFRWcFFtbGtabnBHVjJzdFkyRXdIaGNOTWpVeE1qTXdNVEV5TmpFNApXaGNOTWpjeE1qTXdNVEV5TmpFNFdqQWdNUjR3SEFZRFZRUURFeFZ6ZEc5eVlXZGxMVFZwUW1sa1pucEdWMnN0ClkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEeDJGV0g5NFhLNENYY1E5TEMKaFZ4aXZibXdFay95a09vSWdCcXlKVjNibzBqUW43VldmbXU4TmNDWDRTcGVZZWkrdjJFUmRrd0NhQXBJWUs4UQpDY0RnU3VNZHA2Y0djWi9YcEcyaVlwV1NrTkpIcE5OcUM3SldiUzAvbmtNQWhCSlRnUkIzS25KLzlUY3RsZlBkCjVpQ1lVaStrazRUUGZ4akdaTFJweW1oZlExR2tSZExHV041ZDk5Sy9iQXNJTnZhb1hTT0JVcElQRjRzT3pya0kKL1dqbWtoUDVCcHd6QTl1enhvWHpQbFR4c2pEUjM0dnVic3JKQWVvR3labDBNazBORWxQNncxaTFoM3VseUZHcgp6ckVQbitKelZaVUtLdjFuY3Bra3NiMWVJd1dRT3I1MEt2M3YzdFdFUGczSlZkNFIxbVF4alE1bUdWS0tOeWxmCnZnSEJBZ01CQUFHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0QKQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNRVXFOYjZuYXROVwpCdWIyZlJUSWR4cGNBREF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxEMU5kbUkybDcvR3JiTHA3U0RBQTFNClRlMkcwV2NlRi8wNThwVXFUMHVpbU1ObDNqS2Fxcmp1cWJIZmM1Z1dlbWNQaW1xcEhVb3VBdFA0ZFo3cU1iS1gKQU9hcjcrQmhhN1NHZC9SUzJETWQzUTZENWhaWEd2N0lOa0F5S0ZDaStsTUxLTW54b1U3YlF5MGpTTytkemZGMApvakpYSzl0b0p2L0Rad0RpY01mZHJ5dVJpZ1BISENBeldmYTdPaEdaakFSbTVvdnQ4RzZCMVdhazgwT2lSODVHCnNQMml5SHdGUlZldTRaMWFmZkMyUUtUOXN5R2pqaXVJZlE5OTIzMll6SFJBOUJ3dzJRdGk1VmF3bU04UVpaZXQKc2FXSHJXZk5zR2ZUdDF6MlkwTlRlbnVTWktJeS8vUHlrbElXbjR2b1R0bzI1QlYyUUNYK1ZFaGtxUW5tOVRRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
