---
# Source: kubescape-operator/templates/storage/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage
  namespace: kubescape
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
data:
  config.json: |
    {
      "cleanupInterval": "6h",
      "disableVirtualCRDs": false,
      "excludeJsonPaths": null,
      "defaultQueueLength": 100,
      "defaultWorkerCount": 2,
      "defaultMaxObjectSize": 400000,
      "queueManagerEnabled": true,
      "kindQueues": {"applicationprofiles":{"maxObjectSize":20000000,"queueLength":50,"workerCount":2},"containerprofiles":{"maxObjectSize":2500000,"queueLength":50,"workerCount":2},"networkneighborhoods":{"maxObjectSize":10000000,"queueLength":50,"workerCount":2},"openvulnerabilityexchangecontainers":{"maxObjectSize":500000,"queueLength":50,"workerCount":1},"sbomsyftfiltereds":{"maxObjectSize":50000000,"queueLength":50,"workerCount":1},"sbomsyfts":{"maxObjectSize":100000000,"queueLength":50,"workerCount":1},"vulnerabilitymanifests":{"maxObjectSize":50000000,"queueLength":50,"workerCount":1}},
      "tlsClientCaFile": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
      "tlsServerCertFile": "/etc/storage-ca-certificates/tls.crt",
      "tlsServerKeyFile": "/etc/storage-ca-certificates/tls.key",
      "serverBindPort": "8443"
    }
