---
# Source: kubescape-operator/templates/storage/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kubescape-operator
      app.kubernetes.io/instance: kubescape
      app.kubernetes.io/component: storage
  template:
    metadata:
      annotations:
        
      labels:
        helm.sh/chart: kubescape-operator-1.30.0
        app.kubernetes.io/name: kubescape-operator
        app.kubernetes.io/instance: kubescape
        app.kubernetes.io/component: storage
        app.kubernetes.io/version: "1.30.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kubescape
        app: storage
        tier: ks-control-plane
        kubescape.io/ignore: "true"
        kubescape.io/tier: "core"
    spec:
      serviceAccountName: storage
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 65532
        fsGroup: 65532
      containers:
      - name: apiserver
        image: "quay.io/kubescape/storage:v0.0.233"
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /livez
            port: 8443
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
        env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
                divisor: '1'
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
                divisor: '1'
          - name: KS_LOGGER_LEVEL
            value: "info"
          - name: KS_LOGGER_NAME
            value: "zap"
        volumeMounts:
          - name: "data"
            mountPath: "/data"
          - name: ks-cloud-config
            mountPath: /etc/config/clusterData.json
            readOnly: true
            subPath: "clusterData.json"
          - name: config
            mountPath: /etc/config/config.json
            readOnly: true
            subPath: "config.json"
          - name: "ca-certificates"
            mountPath: /etc/storage-ca-certificates
            readOnly: true
        resources:
            limits:
              cpu: 1500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 400Mi
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
      tolerations:
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: kubescape-storage
        - name: ks-cloud-config
          configMap:
            name: ks-cloud-config
            items:
            - key: "clusterData"
              path: "clusterData.json"
        - name: config
          configMap:
            name: storage
            items:
              - key: "config.json"
                path: "config.json"
        - name: "ca-certificates"
          secret:
            secretName: storage-ca
