---
# Source: kubescape-operator/templates/storage/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: storage
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
