---
# Source: trivy-operator/templates/secrets/operator.yaml
apiVersion: v1
kind: Secret
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    helm.sh/chart: trivy-operator-0.36.0
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.34.0"
    app.kubernetes.io/managed-by: Helm
data:
