---
# Source: kubescape-operator/templates/kubescape/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: kubescape
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: kubescape
    tier: ks-control-plane
    kubescape.io/ignore: "true"
  name: kubescape
  namespace: kubescape
automountServiceAccountToken: false
