---
# Source: kubescape-operator/templates/kubescape/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubescape-monitor
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: kubescape
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: kubescape
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  namespaceSelector:
    matchNames:
      -  kubescape
  selector:
    matchLabels:
      app.kubernetes.io/name: kubescape-operator
      app.kubernetes.io/instance: kubescape
      app.kubernetes.io/component: kubescape
  endpoints:
    - port: http
      path: /v1/metrics
      interval: 200s
      scrapeTimeout: 150s
