---
# Source: kubescape-operator/templates/storage/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.spdx.softwarecomposition.kubescape.io
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  group: "spdx.softwarecomposition.kubescape.io"
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: "v1beta1"
  service:
    name: storage
    namespace: kubescape
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRT1RyWWk2MStZWnovNDdRLzk5eTlWakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRHOXlZV2RsTFdOaE1CNFhEVEkyTVRBd016QTVNVGcxT1ZvWERUSTRNVEF3TWpBNQpNVGcxT1Zvd0ZURVRNQkVHQTFVRUF4TUtjM1J2Y21GblpTMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTUxyT0VHUWk4STdoYlMwTWZCWE5UVFhBVm5BZkg2VHc2ZXFac01LdHZieTR6eEUKMThqY0FwaWVOand3a1oveXlWR0VIVVh2TjdJNlpmVjQrTGt4NFBSY0ZobmtVMis3eCtoZldIUzNHWFM2R0VkcQoxNi9jUmwycmVEL1V6eCtCQW5rVkE4KzRndkJXMUFqYjRiWCs2V09mdTdRWGZvU2NFTlpERWdBaWxUSGJjNm01CnNXSVpFVnJrWDdoSVp2SUhLdFd0Ky8rcTBuZzVFQlFrMk93OVZpZmRWUHJVMFdOME1IV1NFa0sxcEtNUUY2dmUKL0pycWhZYUI4bUIwTklyOUZVMGNDQzRMQkZGUW1yanJ1SkFVYUZUbkdIenlyTkVLdlp1c0k5WjlGRzFVUGd1Vwo0UEowclI5NklqTFF4dEIvQ0pOWjk0bUtjSWQ0czhmRlpZQmRpNWtDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlFuQ09vWkFtazN1VlVjSXdWUkttSTFVbHFXWnpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFoS25aM2srQ0xiM1czdCtkY1NTSHd5dkM1N0tOSUQrSzEvbUF3b0pqMEYzenIyY1lPM0ZmCjVaQWpYaDZXWVpHVDhvaXEwSmJwSnBPRXpwUHExc2RIQ3NsbW41MnErb2hCZU5GdUJ5eEVLd29aaEtjM2pvTjEKeERqWVFxMzJzYVYwZjRLNXpLY3BaQmx1dTdEY1N3STFrL0FSVHJNODFXQll2ZVFpRHc3OW1qSm5abkJPMWhpdwoxalRHOTlod0J3eGdwaHYwN1Y5V2llUmtvVDI5c1QydkN6bWh4eUJKbGh2amtkZ2UxNUlNMUxVS0V6K2RjWVpICkR0V05mUE1sS3NjZkljTjVoRjdYVDJDOTJWN3pwd1JkL1pTY2JxYVI0cEhQTmk0TjdoNCt6aUkxK0kvNTJxbWgKaVlQQ2RCYURuUFVRQytac0x3WC93dXhkbHl2UVZ2c3FUQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

