---
# Source: kubescape-operator/templates/storage/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.spdx.softwarecomposition.kubescape.io
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  group: "spdx.softwarecomposition.kubescape.io"
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: "v1beta1"
  service:
    name: storage
    namespace: kubescape
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGakNDQWY2Z0F3SUJBZ0lSQU8yamJqZFRDVkNLRDNpK0FvbmdBN1F3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2MzUnZjbUZuWlMxallUQWVGdzB5TmpFd01ETXhPREUyTVRCYUZ3MHlPREV3TURJeApPREUyTVRCYU1CVXhFekFSQmdOVkJBTVRDbk4wYjNKaFoyVXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUMxb3VZSDRHL3hSb09iTXNhVEJaemt1MS9IMGFadnlQSzdQRVN6Q1Rvbm16VmEKdG5LMjVycno0M1U4clB3cGZZbFR3NE0xT1FZUS9oR0lsOUdKeVRtNCsvVGd1ejh5d0lGSmwvTW13UjNPUjhvSgoxYkhyTDN0V04yTlc2SEYyT0VBT3BkelFYMVZXeEplMTVSOWxLUlpxNjkybkxHMVZHVXVkS1piOTFyQzM4cUFPCkorMVNpTGx4SHoybG11TDdmWnZyZGNEU1B1bCtBd0N2MlExN0hpV0Uybzcxa0VoenBKdjQ5V1dNN2ZOdHZmK08KR2tkRndjbUwvSjZCQUF6bm1NRGh4dzJhZTRMYlpGUFJDSTlvYmpyYWNQWnFiRURCRDgrMzFmV1pLaE1sR3hsbQpIcmY4SU9MTk1BM0IxbUtCWjBHUmNHYVFYWEZsT1hOVXdOUUZNdU9SQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCCi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVckh3NHlUOVUzdVFlQm0vaFhTa0wzMGF3aC84d0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBR0JkN0Q1dC9BbGxrNityL0hXaXEzcUkvYmtpRERTNm5UbklqYmhYaUlzdCtTRm05NVhECnplK1lKYW5GQzZaLzNPZjdQZ2dWRWRUbk9ja2ZXRmo2QjFlYVE2bDk3ajJoRjVBdkhEUWJOMm5KajcvbkkxaEYKc21weW9vRFZQN2dwcVdCcXlmZ3hNRVMyS1hKajMyVERQRzBXK2tSTkRyZ0xMeHJBVnc3WGE0S1NIWjF5b3VBaAprK1FJeHh0U2hFQ24yWUwrQy9iTXMxQ2Q5dmVHRUxTbXhEYmhmMVUwWWE1L3NJNFNHSWhyc2xXaG1CRVZXZC9MCnBQMzRuVkxsUnpjVDhBQVhDcmJDZEkvUkhTcnJic0Z1dEJ6ZDB4SnMzS1owUGEvRW1LSWh1ZCtQdEJFM1NFSWEKSERpd2Q0QVZrTTNHWnpQNWw3Q2tKSTQ5MmQ1M2oxb2RuMVE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

