---
# Source: kubescape-operator/templates/storage/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.spdx.softwarecomposition.kubescape.io
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  group: "spdx.softwarecomposition.kubescape.io"
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: "v1beta1"
  service:
    name: storage
    namespace: kubescape
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRV2hqZExKTkpnOW5TeVVnbEJmQXNjVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRHOXlZV2RsTFdOaE1CNFhEVEkyTVRBd01qRTNNRE0wTUZvWERUSTRNVEF3TVRFMwpNRE0wTUZvd0ZURVRNQkVHQTFVRUF4TUtjM1J2Y21GblpTMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBSzE3a0VGcFdXQkRKQm5ZZHRpUnEzeUJNSWdaTjlEUUE4NHM1N3hLczRhVVJvVVgKZlMrQ0QwNml0eUQzSFQwWi9sdFJkWUhvZkppa2d3V2laNUlCSWFwQmxoZm1XT29OQlJGeTJYYXh2ZWtETXZ4NwpBZDFjOGlKR2tOekdTbXJPOEs4MVZqQjFCanZvS3d4bkNveEFJNDJPVjdSbWpCWlJtL2FYM0s4ZWwvc2xoUjJLCjZRS1ZjbVZXUi9EeTFXUHZCMS9lR3NHejFzanBCalN1WEg5OWdzaHV0RlJqejM1d2xVRFdqZm5SOHluL09nWkUKS2Q4Qm4wSXpXbnJOTm5EZGxaRnZNTFh1bmdiMnVOMkJBbGI3OHdOTHpQQTN2MmdjRTBWMXlDZFc4K1Y4SkRVVwpQcFJHQ3ZheDUrSHJQZmxLbTFmNzlvTXlPV3R2UnpzQm1Kay9aRWtDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlFCeEhZalM3NzlrbVhrZmdMS0crYmdnZHFFYURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFyVnI2WmJIY01pM1RGeUF2SVJQWUcyeUh3empDdStudzJBejNIVUtVUkFHSVZLeFJ3Nlk3Ck5SejF2TUdCeDBYVlREMmczRXltamxHZEdnVGYyS21LblRkbW5nZElJbFQyYWlkOFlhYWYramxZeWtWOHVQUU8KendUMGhyRXZZMmQ1eWVZeUNQTXpxUE5xOU8xbTJEVlR4a1VDZVlWcy9UQjVxUlJrZFgyRHR2SGhrdmluZkZYTQpEdG5jRzh2cUdpMTd4dXpQZ1dSVzZ1djBRT1cwSTFoV1dBNk1vRjY2bVp2SUI5bXF2OFhkcmpkdjhsYTFZRXI4CldYVDFCTWdjQ1Q5Y2dJVjk0ZjNxMXRVN3N6Qyt5WE9PUUhIM1ZpcFREb0lIdDBMZWhJczhsZ3hYRlR6OFh0a3cKdXAza0xxWU5qNk1oaDl2ZVpQQmY2M2dHVlNjRVJkU2dEZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

