---
# Source: kubescape-operator/templates/operator/admission-webhook/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubescape-admission-webhook
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQU0rTFBIeVY2L1hIT3ZrL2VVV0VPM2N3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUI0WERUSTJNVEF3TXpFNE1UWXhNRm9YRFRNMgpNRGt6TURFNE1UWXhNRm93R2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd0dJbFFTalFDbjVYSkdvMS9yb1dhNmY5MVFkMUtOU0cKTEZoUkx4WTBHUnhMdWMxMlhJQnR4TXFtWE9MbllDZ3o2VkJzVmZWa3VBcmJFYVo2N01FemlFVUtGVmh6dXlCOApzcGQ5U2xYZm5aNS9FNXVrRi81YTRtbk9hWmtPTDQ1RWM2d2Z6UkNkWW00dUE1aXdOUkFHQ0V6QWJBNXA2VFBwCjR2QUc3dUFXZ0l0aWdscTRjYzNsRXNlWU05SzY0TkFtemR6dlkxdVo2Q3FyaWptVEN2eTYxNlVkT0NPcDNOTncKK2lYWGtGZmYvTkRmVlVzWmx4Wk5xMzYrZzVOc0k0ZkV3Rld6SEl0V1hlWHExcUtpOTZFV2pWWXB0RVA1WDZuOAovVGpGbFZhdnhGV1V2N1ZGSlNwNUNWaVNJTUdITnZpQWpCVnZVbkRGRUZVNmlFbCtNbVdoSVFJREFRQUJvMkV3Clh6QU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkQ0d0VBRS8xWGlMSUhFUk93T2JpWlhQeVFRZgpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJZa0piQlJCRHduNVFEdXZqVjQzcXZSRnNQMk1STUt6N0krN2FLCklqYXo3emRFNUx5Q3ZZLytMRmZ0QTZtM1ZHVmd3amxxcndiODZJMkZENll5V0VXMGhsWnVUYVlqbkVMRWFScFUKYms3NElhQWlrK1dFdldGMEV3d0M5VTE3RDlUWXJLbnpwbVJGSzJ5VXgzV2phMndtMlBTRmF2Y0dXWmE5K2YzRQpoTzI1Zk1IaXljQ0RPYWxWT3VzbzdxRFJ1UUd6Rk12SVloT2FXUGVqY3J0OG9teENLdG9hUERiU0UzVUhnRFhzCnVFVlpwN3g4NE1oNmd2akhhZUZpY1FZc0EyMndTYUMvRGNxNGNOU1J6UXlRZ0d5UVg4UjM1MFNWWHdKQkNkbUEKeEkvNWhuRlJoRi9mdzNHYlRGZ3ZBMG4vTWFDVkFOU3B1c3piWmtUNEZHdUZpbThnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
      - operations: ["CREATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["networkpolicies"]
        scope: "*"
    failurePolicy: Ignore

