---
# Source: kubescape-operator/templates/operator/admission-webhook/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubescape-admission-webhook
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQUoweTNGbXdzK01YSko0YmlwVFJVa3N3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUI0WERUSTJNVEF3TWpFM01ETTBNRm9YRFRNMgpNRGt5T1RFM01ETTBNRm93R2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeUJvVEZwU3o0TDVkdHYwN0JSR2xjNExQS1dQUGZISUIKRVFyWStRd0dvYWZLa3JTN2RhUmQzS0tpRURqZVBUOExkbTR2bFdkNno0QWg5OGI0NG0yYklSYUZqV01lQUdjbQpXZFFKeERHaWxYSWRRcC9MR2o1SVRHV1lWdTdZYVFOTTNrTXMyckFHbUpJRkRVMzhiSjNVeENVTi84aDE0NVlzCldOUVltUlFDU0FYUG4raXVPU3VlOTlPUldZUUlzUXRSMC9oTXdGTHlFZXFpNWVHQTZ6TWp2MUh6K3BQQUFYUm4KTEhNb3BRMlVib0lpVVhVWmIyRDE5dmxRdFlKSkMvdUNTeTRMUHlFemdMemdrSGVKdk8xSjFZeEh5K3dVdURhcApMRWlGRy9jOEFSRkczTGlMS1ZMeS9Ub2Z5Nnk2TXF1SFU0U0dpK3h0NkNtM3pUYjRybGtNc1FJREFRQUJvMkV3Clh6QU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJHNWpGUCswSHhnZFRSTXJpQkxQMmo1OU02QgpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNrd1QyUEFRQWFjdTAxQlRrVFhRcVB4QXZLVDRrdExoVmdtLzdlClkyQUFBNWFxd3dycTFlOXdIeGg4eEVmYzlrV1lMY1ovMHFvZmp0ZFFEMlV5RmJ3TEJWMWs4VERBNHJBZUFPcWkKZzZpRGdxWi9OWUJrdzRrdGdkNG95YklmU3lXL3BHczVINDMvNHcvZTR0VXdJcFYyTG1xREVNYkowaGZqYmx2RgpoYWpkOEVrMWlvUHlYQWdPdU9wcjFJNEU5S2xoZXJVN2dmZm04cUdibW0yK01mRXRRYmRPVS9DUXNFUTB6b3pBCkNhR09tWXFNT3k0bTFNZUI5V0IxNThpNHZNSWZ5TkZCN002SE0zdzlBUFRSMFFTZU9RTWgxNWFFaDRjQVQydDIKMTBsa1J5K2UyUlc5SnRkV0haZitmUUU4OVNxQi9HTSticmQxSkJ5TndERlhTYnE0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
      - operations: ["CREATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["networkpolicies"]
        scope: "*"
    failurePolicy: Ignore

