---
# Source: kubescape-operator/templates/operator/admission-webhook/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubescape-admission-webhook
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRZndBdklhY2RJVWtwV0xPMWNUK05RREFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13SGhjTk1qWXhNREF6TURreU16TXhXaGNOTXpZdwpPVE13TURreU16TXhXakFhTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN6L2lMbmpYa1lmNzV2NHBIWEk2VUJBRUtONk5yMFdGYVMKUnRjd2lSaUFHbmdOZTcrRDVrdHdvR3BKTk01eHNkNEpablJpUFUwcDhtd3hmVGFVQUY5NVNiTnZsOXZPeVcwVQpZRERRdHFsWXoxTFl5ZmhYTXpWeTBSUEdkTzZLd0JIN0NWeHVpMDhOQ2kxbGRTR2FQalE4Z1Btdm1HV3pGZi9mCldUajJvc2dTdWdiQklBQ1N0TG5weGtvTnpNZ096cXArblNZUXR4WTAvNnYyWWlOellucWRJK3ZKUWJwdEk1Y3cKRHJ0VUlqS2xFMllZY3RIWE5vc1I5UzVPa0VIQXI5OGQraVpHL2FVYzd3cVFjWU9TTTRiOVNSNUhBa1lnaDFKMAo1Y0NzaGRyZmNMTS94SUJlY01SYnRCUlJ2cnY1WTNQL3FtbjBBejEwc3NlTW5xQUdUKytCQWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVeWZFTm9GN2plUkFvQWtlRnMvcS83bWJHTjh3dwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS2hvTmxQcStsSW9YVkpHTnFWN1d4eXhlcTVnRzJtR1JPQzVqdFdqCjdMU1dlM1hEQ2puZllleEE1VDJjbTZjVWhEZktkSnVFWHcyeThlTWV2bng5MERqdzY5U1BRQUw5RGRTQjVka1MKLy90UTgySGNRMEZBS2VNOTZHQXpvNlo4TDgrNEk0dkFqZXVBbmJ1M3JET25rYU50OHEzZzdwN21wc1NxYzNUTwpmR3E2ZFliamYrNUtHOG5Vbzc5Y3dicDZpamFjcHJhdG1tMXJENXpBUW5mUjRsSSszQUpjQXh5cUpmSWxndis0CjU0dE8wb1RncUVhTWg1VlppZUxqalc1Z2pRZzFJUnU0MkowZHhYTU5pcXliQTlxUkNyWTZWTVJlajB3MFNMdDMKQWowNXVKWC92TmVLdkFrcE9xNTRlSGMrZUxZRTIwcnZ0NGdlSENGQnpPTTVlSFk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
      - operations: ["CREATE"]
        apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        resources: ["networkpolicies"]
        scope: "*"
    failurePolicy: Ignore

