---
# Source: kubescape-operator/templates/operator/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubescape-admission-webhook.kubescape.svc-kubescape-tls-pair
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMU16YzFneklVYUx1eTR2VDNOZllicWIybEJQK2tSZVFrUmpZZG9SMWFRQjJWZHk0ClhGc3RsVFByZDV6OE1QZUV4TnljdVRTdmpBaWJSM0pjMnVzRXo5WnZvNVJiN3dJbWhGekRtdXhaMVNSU0hscU0KOWlDb2hsU3RzeGVEUWsxK0pub2loNERIUHR1ZmJEeTA4M1Z0bjFGMUxYQVNGR0hObzNqVlprRTl2Z2VhWEVMNQpzL3BqVC8xN0NLbnlJVXhNbGpvNzlDYVF1Rml4UVl4YUdpVDZXRlZNMkVoWjFTcTBoWjhxRkF2M0IyQ1ZvRlFUCk5KWTNVYzFxT1ByZUxuNEpGQzV2UUNwTkRFWmQwcm0ydWZGekdVTkltbkdMYWEvTjFkMDlLNTNWRW0wenFjZzMKYmQwMVZYeXlUOGlDaVpsQmx2SUxXa2JMb1FYdlVnMGtFRTFMbFFJREFRQUJBb0lCQUFUcHFkdUROZ2kwYzBEZAp2SWxucmtaM3NrK2Uyb3lzOTVoeDgyVmhEM2phR3VGR2xEY0ZuOXJHOVJPdzJ4MmlTVDFtUG5RRUpGMWVRWDkzCncyOEdaL2tJWVZGc2RtYmhMTlIzYzhpYTFrUVdiNUxsMGtWSVlidWdMdFpvbjQ0alRkdERqSktHUlpOTTdMUkoKL245MFlaQ0JCK3lCbnRrN25NeStXR2JnOExUM1d6Q0dERGMwczhXU1JCbVZMczRWODUvbElRVnIyK21Od29vVQpRc1d1SnVuMG5Gb09LcGN3dEpST0wyZ3JBNnhGYi9mVGszSGJ6RzlETjZMTDBHQURPekVXckJuSFhTSlYzai9iCkhWMkJtRnE2OUZXTXUvc0Fma1ZqeUFmeHFhOGxvMGR6OXU2ZkZBenRoTFdpcytYWDFRZWFySHNmc1Q0UGQyR0YKeVdIdDErRUNnWUVBN2ZyaHVoTGhVTnpBdlBUMU5tS2t2WjFVaEtqK0IyUjZSS25qYVBGajYrUDdEUFp6a0g0UQpEUVZkRHR6RHZIWnRpNGlVOGRuRlhUekRtYVp4OWF2NGVFa0FUZThFTERtRWhkNU5odlZvTXQ3Snk2LzB3VU82CitWWnNwdFBQU2ZicTdHK3VYSWhHODBuRk9iZm8rL0VEb0lSVi9iY3ZhL09neDU5RUc0RWs4czBDZ1lFQTVPbmkKWkhqWG1Ha1VNS2F4Yy9WWTdldG5LeHBIbk9LUFpGUXV6Zm02c2cyUEtFQW9ReHFtU0pQczRNZzNLcHp4cFRScgpLVHZQbml6SkJ6aklWRkhiMHJwSWZrMENjUk00M0pIaTdZRmV6aUhqWlhza1lKeW5vT2xackk0QXNJaHJYVFVuCktCOUlUK3ROblBIOHRRaWtDR0ZXZjErNFkvTDhXRzRQeG5Nemkra0NnWUI5RDBKZ0RsdnBxcGgrdEJ2SW9MNEMKQnhQTFF5Tjdyd214MjdWdUNLeUI0aVNrQXo5bngxZVlBQ0dQRmVTbXZYV0R4aHEvbmJsaDdmUzhZZ094SHRaTQpIOURSSTdJRnE1UkE1VG5JbWw1UG5WUmVmZkVaUHdhYTBSZjM4NGNUVDNiVkdUdC8xUDIwRENoZzFJelRHU3pXCnhiU0t5Q0Zia1lRRVkyWGZMbGJFWVFLQmdRREpscmFLYUdqa2pWVDhheS9Hd0grcU5pNUtwUC8veHYwa0M0YVUKV2FIeC8wTGMzWE1YZFRhT244WnhSYUJmWklyaFE4SkRNNnJvenVQUitrMWhCQjJqKyt5dlhUNFRPaXhQQWlKbgpxaEJGVTA2Z0pjdXBVUXZHQnZtem5mSTVoRW1ZY2FDa0VyaHB1UHhHaEV4WldOeXJqSnpSMndmVTdUMFEyd3dGClpabzFVUUtCZ1FESC9EVEhSaXVYcXFPSURhTTN3cHI3THZudHViUnJWbE1WMmVuZitrME51dW02RjJsRm0zZDcKS0xHeGtSVDd4ankrTTNKcUlmSXA2Tk15TVI4RlVRRnRmRkwzYkNJdVBCK09KaW5Uc1dvTklYUzZuU2d1aXY1NgpqZFNEK2FFalpzQmR6TVh2OHJtSVZwMjBlQkd4UnBIbVQ1blkrbkxIVlpFTnZkbTliRXhzTUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjVENDQWxtZ0F3SUJBZ0lSQU5Fc3IvdEt5OUpNTVBhT2JEWjhaRWt3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUI0WERUSTFNVEl6TURFd01UUXpObG9YRFRJNApNVEF4T1RFd01UUXpObG93TkRFeU1EQUdBMVVFQXhNcGEzVmlaWE5qWVhCbExXRmtiV2x6YzJsdmJpMTNaV0pvCmIyOXJMbXQxWW1WelkyRndaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUIKQVFEVXpOeldETWhSb3U3TGk5UGMxOWh1cHZhVUUvNlJGNUNSR05oMmhIVnBBSFpWM0xoY1d5MlZNK3QzblB3dwo5NFRFM0p5NU5LK01DSnRIY2x6YTZ3VFAxbStqbEZ2dkFpYUVYTU9hN0ZuVkpGSWVXb3oySUtpR1ZLMnpGNE5DClRYNG1laUtIZ01jKzI1OXNQTFR6ZFcyZlVYVXRjQklVWWMyamVOVm1RVDIrQjVwY1F2bXorbU5QL1hzSXFmSWgKVEV5V09qdjBKcEM0V0xGQmpGb2FKUHBZVlV6WVNGblZLclNGbnlvVUMvY0hZSldnVkJNMGxqZFJ6V280K3Q0dQpmZ2tVTG05QUtrME1SbDNTdWJhNThYTVpRMGlhY1l0cHI4M1YzVDBybmRVU2JUT3B5RGR0M1RWVmZMSlB5SUtKCm1VR1c4Z3RhUnN1aEJlOVNEU1FRVFV1VkFnTUJBQUdqZ1pjd2daUXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEcKQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZApJd1FZTUJhQUZHb2FBR2FUc2pWdWFpdnhOd1lPcVBaTEhISUNNRFFHQTFVZEVRUXRNQ3VDS1d0MVltVnpZMkZ3ClpTMWhaRzFwYzNOcGIyNHRkMlZpYUc5dmF5NXJkV0psYzJOaGNHVXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQUE5SjNGN3NDWEdxMlp1NnVZY3RqYWFMR1JkUFh6MzIvbWFmMW1Jd1kxVjYveGx5ZERUcFNDQXFpbQpQVG4za2Rmd2doSC9VNnV1OEk1aWc3Y1BJd1JtK0xtY1lpZm5MS1lVWXQ5S09jOUdDeXB0dHZ0RWVINU90ZUxiCmM0c1VhNnZUTWQrTjBWYXAvMEsrbitadUIyQjFnZmZWaUNvbjZPMUJXTWx4RDJ3K3NlWDZzanlic2NLQlR5dFEKUi9rSGtGWkdsb0FGQitacDJ4SlU5WnVxRUYyNmpmRTZ2M3hmZFVXMnVPdEZKQVVOSS9QYlFmTHFVU05wZTBWTwpOdzVaM0VEU1VEZTFTTE51bmxUKzdzTXF2c3k5ZERyWllMQnBLczFJUUh0d3dCeTZGL0traXRRT0hzaEMzZ1hkCjNWYndCNzNtbUNxanh6Uk5rVG5QVko0VEVQZzQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
# Source: kubescape-operator/templates/operator/admission-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRQlVubGIxMnp2TXA1ckU0MTZYY1ZmekFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13SGhjTk1qVXhNak13TVRBeE5ETTJXaGNOTWpneApNREU1TVRBeE5ETTJXakFhTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNnT1VRYVY4aEhkUUZSU0NtdVc3Mms1RTBYb2didUhkKzQKK1ErSWlFc1Y5ZnZVNldQdFRvb0tPdmZTaEptNFl3bFd4K0REN2VubFdNQXRjVVN3VUQzTk91YmpIaXZ4bGdKQQp4RXJ4S2JuRGwwNjNGOE9ZZysycVNxUEt5QlBSbWZHekpNNERBWXp3ZHJZZVlIMWprRWJXdTBWOXgzZTZ0cU9uCkNnTXVwVFRRaGZUMVU3bi9lYmVRZWNGRFZ3R0VkOXlNOU9PYyttck83RTB5ZUgydlFhbldreU5DRFhzbmRRT0kKTkVURW8yN0VLczlRd3JUTTFzUEZzZlpHbC9uRnJ2TlNIVDJoc1VId255SFA4R0JWM0dVdFFvSnBqUy9oaFhkWgpYamZ1MjdYTFBKb0tqeUdNRzlrdzNjNlcvNFAreDdDcUd0czgvbTdXZ2VlcWhVZTlERnl4QWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVYWhvQVpwT3lOVzVxSy9FM0JnNm85a3NjY2dJdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQkt3WUlqN3diZ1lBMDVtdFM4K2doWkk1aVpqN2VHZDdjWC9HbHZRCjlpMTduYUx6TmJjeXRWcWdUamgvRWdSdm1xbnd0VnN4TW9TMWw0MktUMkZoclJrY0N6WXRVVHBLYkJ4ZGRhY3MKaUJKU3ppT2REenZDWXAyYjNRVjdzRlIvbG5IdDAxRGtHNE14UG0wb0xIdGdzTW9abUZKMGpSN2lZVFAzZHdMOApBbHhrbFlZbEZsa3VTaUhiTG1mSTlRNUh4ZnYySlAxdWlLQlFLMStqMkN3cVNzVTlMTExFUDRpVFVIc3hpaHVGCkxWSTRaY2NOTi9kS2pvVXJEZFA0UXJHOHg3UFpib0RqZ0QydStKQ3MxTEpZc3NJRjdkRFVsSE1VUEJMcmcrZS8KL2tRM1lYcDlzam94aFRqVFZ5ODdnVDlQcUhXSzZWM0JVL3N2U3QvcnArQTVCa0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
    failurePolicy: Ignore
