---
# Source: kubescape-operator/templates/operator/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubescape-admission-webhook.kubescape.svc-kubescape-tls-pair
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd3o2WlZIOWFkQnVpc082QW9pRWliRTlFdWJKR0dWVS9kMGlkelBnREYxWlJLUXQwCm5lSlVibTZWaTNpVzkyU09BMW1vUlVvUmQwVFNQSlphTnJpM2VFaUMxVU4xNjFMT2VXY1dqcFdkZGNDbW4vamMKNDcreHlRUWk5bWFRRFlLeXFlcFN4VC9LWWpKSE5sOVpqbUtqcVdKYkZRRW9DSDN5U1FicUlPSFMzRy9helBUcwpQdEdhNGd0REx3UE9rbmFxRG9JTm5TcEQzRlFnUjJRSWJraU5CUkVPdTBDdXpIMDkyTkdINEVHdmZhaFE5Q3FsCk9zTUdWQlo2SUZIVDNOd3RteGw5OVRiRmUvNlprbE8zZkU4TVpMYm1HV2lybXBpRW15eEtwS1FxRDlLRkxhelAKOUNjZW10UmR0S0FBODEyTDVOT0xpYUxuUWJ3b0x0ZjVNN0tTK3dJREFRQUJBb0lCQVFDR1NjUUVUaVBVd0QxQwpISWowK24xR3FhN0hXa3JFbWRHeEpZMERzWUhPeDF2RE0xSGVWaEZrYzBNQVRzem5FNDVwMTN6WlMzeC80Q0lKCjhnL1NtM0gxbFVvSGpRTEovSVp2RWV4OTNZSVR2NUhiYmJ2Z0diVWFZWEg2cjhoY3dveElPaGI3L0VnakNoblkKMS9RczdzTktlWS9UL3B1ZVc2SU5nR2dBZmRJZU1zMWtkeXRhbVBDMFZWYnU2OU5WTnU0WE5QS01TTmVPa3ZTMgpVWlNScU9xTnVsWllTT01ObTl4UXk5cmxENklGaittRVNxOWpFeGZUeFBXdjdYUE92Unc0NVZwVFNqRGlucXpOCkM4Ty9LVUZwZ29xZFZYTENyQXFJTDN1SE0vWlVwTWJMMkRyVHpuY3kwcit4WlBpM3Z4ZmdTWUFrNTdyWEw1U1MKaml3ZzhuSUJBb0dCQU9MQ1BDVG9PYlVPbFA5OFlsTklMd1J1OHZTTUx4M1FjRDlDRFcxbkdYaUpzYnFTcTRGNgpmQkQ0SFpUN0h4ZVlDRmJVRHZUM1ZOQThva2tJSmszbnhLZ2o4V1VCeGxoQlhka0cwcDZDM0xCcFEzRmFaUVBpCjFNVjBWQlFmN0N4UTBVbnJiMXIvaGdpcEYrSjdrUlhlZkkzQkZHT1RCaDNsY1o0dEFDcnF2K3BCQW9HQkFOeHMKQkMyVUNxdEEvaDROelVwT1ZWbHd2b3ROMkFkYjNQUk03Z3R2NFFYRTFhOVVseHliNk9jRXh0KzlRSW94Rkpidwo1cFBiWHlmeC9SOXFWOHp5a0tmQnk5Nis3OUxjY2VtZWcrN0ZuNFNQNkhpNDdQdWNtZ2YxZzUyam84T2gwWHV1CllTRmcrNTZPNGZrZTZESTZTNCtyWWhxakxFVVB6N1ZvV1o2SjFoWTdBb0dCQU53dVptQWY3Z2pVdy9EZ1FrbEQKeWdPd0I5RlZYVnJCem54ZUV0T3NUSnN5ZUpVRlhlczNsOGlTWTRjSjRFTDBxUVJHbk05WWFjNVpVZXRBTXBGcQoveFdVOFF4M0VMVVpvNXJjZVI3WlNwa3hYUDl3R3E0UFR6TDdwYmgwMXNxaEh0ZDcrSUNQcFFJN3pxbG4rcFVWCm1ETzh5Nk4wVzNna0ZwTFVkMWswNEcwQkFvR0FkUkxtTVRNMWEzcHN2cGZFRnhoK0dyQllkSE1YTCtscDlWUTcKQjFZWUpkRkRVZ25TN1Q0ZU9UMy9SMjBrcjRHY0Z3UEM1SHViRWdOazExL0xYSzdsaUVUVnZPeWJRdHNWb2VrdwoyQXlkU25LSkhqM1NtVjIzTGswSDZCMjNhTHcxSU1VaEQvS01FczUvVmF0RjF3L0JmSUNoN2RZSE9ITktkbWNECldzS0pOR3NDZ1lFQWpYQmVkcjRxYWVNcGtnZE5iR3VLbTNhd3h6Y04vOXVqa3lSSVVaRjJlV1JxTjNlV3hDMEgKcVZYNmJMMVlneFRuUHlXOGczNjF1MHZjdjRCT3dkUlJsWHF6TnZkcFJHRThnNDdsd2JubmNrRWZwcnFpQ2lrdApXS3JNU3dnSDdyREYxZzlOeE5NVmxyb3huZlVHUkV4UCtHakNyOEZjOE9WaWtZRHdkQnRHcXFFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjRENDQWxpZ0F3SUJBZ0lRYjlwS1d0Y0taek1oVGNvNXFudnNXakFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13SGhjTk1qWXdNVEF4TVRRME1ESTBXaGNOTWpneApNREl4TVRRME1ESTBXakEwTVRJd01BWURWUVFERXlscmRXSmxjMk5oY0dVdFlXUnRhWE56YVc5dUxYZGxZbWh2CmIyc3VhM1ZpWlhOallYQmxMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU1NK21WUi9XblFib3JEdWdLSWhJbXhQUkxteVJobFZQM2RJbmN6NEF4ZFdVU2tMZEozaVZHNXVsWXQ0bHZkawpqZ05acUVWS0VYZEUwanlXV2phNHQzaElndFZEZGV0U3pubG5GbzZWblhYQXBwLzQzT08vc2NrRUl2Wm1rQTJDCnNxbnFVc1UveW1JeVJ6WmZXWTVpbzZsaVd4VUJLQWg5OGtrRzZpRGgwdHh2MnN6MDdEN1JtdUlMUXk4RHpwSjIKcWc2Q0RaMHFROXhVSUVka0NHNUlqUVVSRHJ0QXJzeDlQZGpSaCtCQnIzMm9VUFFxcFRyREJsUVdlaUJSMDl6YwpMWnNaZmZVMnhYdittWkpUdDN4UERHUzI1aGxvcTVxWWhKc3NTcVNrS2cvU2hTMnN6L1FuSHByVVhiU2dBUE5kCmkrVFRpNG1pNTBHOEtDN1grVE95a3ZzQ0F3RUFBYU9CbHpDQmxEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWUQKVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwagpCQmd3Rm9BVVBEUTN2YVRYR3pweFFXT0g3bTgrNmJwK1FGSXdOQVlEVlIwUkJDMHdLNElwYTNWaVpYTmpZWEJsCkxXRmtiV2x6YzJsdmJpMTNaV0pvYjI5ckxtdDFZbVZ6WTJGd1pTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQUQKZ2dFQkFBcERsZmZ3SFZ3TnhYLy9TUFdPREk4cUlMVmk0K2lOUXN1SGNEUjRzUUNUYkNWTzgwYiszKzlnTHlZRwpVNzkwT3Z4SjA1RlJ4aXJ0eW5XZUpMaEdwVVRzUTQ2dTJyeWs0T3FGT2lhK2UwQ3dXSHh1QzFKdjA4R0tTcVovCi9iLzdSaFRHR2lXR1l6SGR2NTNvN00wdlJwbU1ENWpEZG5Dc2NLbjNkdnkvV0hMUVo0YUl6Mmd5alhOTSt4aGYKRUN1Y0pIUzYrWEdHQnhia0JVdVQ1b242MmxXbDB6Skd5YytLOHNlM3M2eHpkcGZ0VzJDVUErbjZyd2NjeWdjWQpId0hlUVRDZ0RPcHJwMThzZzJSSDFnbFpjNy9Md3hGVFNMcjR5Wi9rL3lRRUNOK0xIcm5WNUtSTHFGMEdsa2ZNCk5DT1h1a0xCMExqVGVnRkE4RXQ1cWZKU0h4MD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
# Source: kubescape-operator/templates/operator/admission-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRY08wY2RkcWZJbzJ6bVZDQmN2NEtJekFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13SGhjTk1qWXdNVEF4TVRRME1ESTBXaGNOTWpneApNREl4TVRRME1ESTBXakFhTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMzTXpPME9QV3RuQmNqdHJNWmZVdjlLRXZXb2NFanIzVSsKK0plRXdhTlY2aFl1MWJuNkxrOWQxTkU3dVVZaitDblVGZFBmbEk4U2h0ZTZpV3JFNkF5WCt3UW5nbWJVVW0vWApTRFpOMWJEazFtTkk5Skw1S2VRNDNXbGdsVkxXS1VKNWNpOEljTkNjU2N3S216YVJXV2gxR3RKSWI0SXZpWmhlCk1Jc3lodHZXVEZick90TGZVeWJRZnRpSzBVVnhLY3MrdDRMU2QyRmJXeXVTWnBUbUp2c2c2eG1NM3NqVlZaZVIKbUpiQ3FrNWgyNm1oSkF3TmhITzFoRG41QTBoeFdzNnZNcEtKelNtemRwTlB1YXA1M0t6Q2o5NUt3eDhSWnRjbwp5c1FGZmVIWEVMT3dza3h4elU1eHczNFRYK0ZzK2VkRHo5K0VGQnRIZlpaRGRtbjhDalk3QWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUERRM3ZhVFhHenB4UVdPSDdtOCs2YnArUUZJdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRmNYZG9vNThScXpRZUhiYVFIa2Z2cHNMYkFSQnhKVFFMbFhnSGtoCnVPWjdYeG1JSzFCRHFtZVhndU5aQk02WFErVzNkVjlJR3BuUm1RdFM0SGpkQ1A5cVkwU0NrMVZpcGFDcFc2S2QKZ0RuYTJYMU9TUjBNV3pKVlhkcldSQzBuK1BWSE9nODRRWmJ2akFrRVNJeFNUblpMLzh6VEN0V2FMUXFLOHRVegpkNlRiOGI2aHd2b0RuZnU5dG1UUnBaNVdvc0E0TlcyWEYvUFBUR08rZHJDaTdBUkkwRFNGMjVwV0VUOE8weGdGCmVuNlFORWhDdnRjbGdCVUExRUZmRS9xNW5BYVBHc0R2ZXhxTlRycFFMaFFRS2ROR1pXNDlGbWw4dE9kcU1oRXEKQld2eGlkWlJUN1dwRDYvVDZXcEcvVmJMKzhWTnRZQ1RySW5MenNINm44MVZGMTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
    failurePolicy: Ignore
