---
# Source: kubescape-operator/templates/operator/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubescape-admission-webhook.kubescape.svc-kubescape-tls-pair
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMnNmSzR0WlJGcVFBeGxtdEZEN0J0YmlwQ0hYRGlmWHJQMSsva1BzMlExeEVHWWF0CnNod3hCMWRmVXEwRXQ3dUR6YUlVaElTaHg1YzlqelM2dmVIMzdGU21pbGF0bm9qWGVLSlJybHdKeGJiWkpqRXIKOGJMYThiZkFYREoreVFuUGRvajNicjRaTVoyUkZ3QTg5T0k1NVQ0Wm9lQ0ZYVExlL2NsQ1VrZHBGenBxVGNWNgo4OEJnb2JVRVQ4akhQMEJIbXRzMENMaTU0aGV0S0F0cWhkL2NkSDJEZVRvUitmbjdwNDVueHBCVXVsTFF5cjJECmdDT2xzRmZML3drMVN4VjZEMk40YXlRNm1nZDdXdUhVK09TaGJJaEhCM29tVlJmV2hQK0R2RFBsWWJjeFNWanUKR2Z1TzVvQml6Sm4yTm8rWC9KMGhMTG9DcklVY1pMbG9uRCtVYXdJREFRQUJBb0lCQVFDbHRqOU9vZGE1dDI5Kwp6ZDN6UDdXcDF6enhVNEhRdFp5Q1hCdlZ6UEhGQTlYeEg3bmc5c21NTGZuZHZYK2RTME1DTm9vajlmSTBJN0pWCkRqT0VMK3lCN1h4WHZGKzFmU0Q0RnJxWHZzOElHdjlQbGw4YXE4WjY0QnVydWZPZWd2ZkphT1ZCMUd0dzBWQmMKZzZtb010SjNlUm9oS3RiWlNQYnVjOHJ3VjNhYVNCWGc1bTd3SjI0TEh4U1Q4ajJnQ1lFeU5oMVRvbGlXTGJXTQorZ2F1R245MUdGTmU2SCsvQXJJS3RPSE81MDFpdUZ0MnE5VkpvZkw3NVJUZitzWEpzWjVONU4xZDZtOEtseSs3CnNibnVoUVdyZCtIM3ZXU2JWbkpjQUg0Ymt2eHVoRkltYzEwVXQydXc5UGp2Y3FNQjZ1b3FBMWxwMjRMcWhDaU0KYnlpaVErTUJBb0dCQVBnNGdjQnBSQUd5RjBqaGN4cEVXU3Y0NG1hOWhJdWdzdmlzTXprZEpuK1lIdkR3ZVBNNQpHajJaS1lndS9QQk04Wlp2VDZTK2FEVTJMVXN5enBsWG5HVnMvbHBXSWJpU3ZOc1NnS3Iyb3l2YjhtWkRNYllkCnVuRlBTOVc4OFpYSWhNRTN1NjdsUk9Nbk9JWlV2ZUlhWVc3MmxTZ3dNQ2h5UWtLODJVazBpalRiQW9HQkFPR2oKRllXSWJtOXMrRXI5YTVNNVZFU0tZRndJdll0K1lVMStDSWNFVEYvS3k0ZWxjd2NJZTgvNXBiVEovSE91azl3VwovTU9mYVFaMUxIQXZzNVljWEp6OXplVEMvZWNmcEc1RHF6RUZjQmx2YldzRlk4K0VLM0huZ1VzL2Zaam5pay9WCkwzd2taTkNXZVZ3aXozdUVuTlQxSU9wYXlSTXNKKzlRQ20wZ1JPdXhBb0dBWWNKSGY5TTFnSUYyWURMQ2xWN0QKeStpcXFoSUw2TDN5bnJPYlBPdzVKRmx5SGl4blJrdUFCVENVUmRsVHJ3UnV4WE96WjB2Q1dPcXNiZ2hsaThrUQpoSFdudTBaZTQ0V1BNYXlZMWp4cXlUUkh4SFRFV0ZoZS9JOWhhNTJOZkJOTURaajRwd29PMW5PMDlGcmRxZlgvCjE2YnYyYk1ZMUdVanFZc2MvSkxmdDY4Q2dZQUhQWXQ0UUh1Q3VkVngycFgwSUhmU3h6bjJXaFZ5LzNneDIyUjgKcUtlbXYwUXVzeUZ3elZYanc1Z01xQnFndjY1ZzlwL2Z5eUs4b1UvdXZha2VuUVJmeVVrdEdSQzZ0T282MjVNSAp2S3Z2TlFNbTF3SnY2MGJWbmQ4cFFmMU94Y2RMYm9UYWovUm9PUnZsMS93ZWM0L3d5WGpuN0VmZGhLSTNiTE1ZCjgxc2kwUUtCZ0c2Vzh3T0tUa21qeWJKcSsyUDRwNkgzSUFPSHZKaU5uMDkxcGRTU1p1MC9keElmZnNhZHBsRmQKWXF1RjM2TnpFSjViWmlzSm5EWU00WmUvU0EveGZZc1J1K2dsVHlwYi9SVzZCUmpyVjQ1TWpjVGRFWUVpQmxHdwpNamNGTGU3eUlFTFNOWnFiWjNwTGZHR0xjTGY3SDhONHVHaFBIOEpyKzcwdVVtUlN5VmVnCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjVENDQWxtZ0F3SUJBZ0lSQUw2VnhtQjFnNkFOU2NFZVlxSVlQWVV3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUI0WERUSTFNVEl5T1RFNU1qY3lNVm9YRFRJNApNVEF4T0RFNU1qY3lNVm93TkRFeU1EQUdBMVVFQXhNcGEzVmlaWE5qWVhCbExXRmtiV2x6YzJsdmJpMTNaV0pvCmIyOXJMbXQxWW1WelkyRndaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUIKQVFEYXg4cmkxbEVXcEFER1dhMFVQc0cxdUtrSWRjT0o5ZXMvWDcrUSt6WkRYRVFaaHEyeUhERUhWMTlTclFTMwp1NFBOb2hTRWhLSEhsejJQTkxxOTRmZnNWS2FLVnEyZWlOZDRvbEd1WEFuRnR0a21NU3Z4c3RyeHQ4QmNNbjdKCkNjOTJpUGR1dmhreG5aRVhBRHowNGpubFBobWg0SVZkTXQ3OXlVSlNSMmtYT21wTnhYcnp3R0NodFFSUHlNYy8KUUVlYTJ6UUl1TG5pRjYwb0MycUYzOXgwZllONU9oSDUrZnVuam1mR2tGUzZVdERLdllPQUk2V3dWOHYvQ1RWTApGWG9QWTNockpEcWFCM3RhNGRUNDVLRnNpRWNIZWlaVkY5YUUvNE84TStWaHR6RkpXTzRaKzQ3bWdHTE1tZlkyCmo1ZjhuU0VzdWdLc2hSeGt1V2ljUDVSckFnTUJBQUdqZ1pjd2daUXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEcKQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZApJd1FZTUJhQUZFRU1naDRZWUFXZFcrU0RId0tXallsZWx0VGpNRFFHQTFVZEVRUXRNQ3VDS1d0MVltVnpZMkZ3ClpTMWhaRzFwYzNOcGIyNHRkMlZpYUc5dmF5NXJkV0psYzJOaGNHVXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQlBETDhHYXRYd0RNUFVPOHBaL0IxNTA3ZC9UVlZLYUtiMEZDcGVDRm4ycVFZb3h2WW40RU1oMlZvRwptWlkvemRKVFRNSlcvTCtUeDdidzMyZ2NCS3NLZFZ3cktRNzQzN1FtMktMdFkvL2pNL1BWalBPb3o3OElrUGJTCjNoQ3luelBRcjNWbUkrbmpRSE56SG1ob3FGcnhRV3RFRzAvL0Rzak05THlwSkVwOFR6eXhzLzdzcGpIanUwQjkKbWJxM2R5dnJCVnhIY1Z1cWdwWWl0Vm05U09BcjVGQjRFeExISWszRXI2cWVjUTM3M2lLSVY3QjdXcWsxSVRvRQprRFE1bzl2MnN1cHUrbVZxNFNpaU5za1I3ZVJzUW43Vlo4NXB4anpuNnVaMlBseVY5WC8zRHA3djh2Mlk2V1VFCjMxWWE2amNIcmprdlM0bFRjUW55OHNKaXVOeEIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
# Source: kubescape-operator/templates/operator/admission-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: operator
    tier: ks-control-plane
    kubescape.io/ignore: "true"
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQUx5Umo1bXdWZWFZeVdtWWU0OHNSbk13RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUI0WERUSTFNVEl5T1RFNU1qY3lNVm9YRFRJNApNVEF4T0RFNU1qY3lNVm93R2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdHlFVGgxaGNkN0s4L1ZNNXRldGF5ZWFKRXlESm5TaHEKRTJHRTFOYTlhYlhiRjhsWHNUSHErSzZrZUdSUm5teVVhQldGenRGMGNrVXl3ZC9nVGRzdmJHbGg0eUZ4VzdGYQpLVkJZVXlQaVdzV3lHT0drNUl5ODgxelRuMkdGSmlmSHI3b1U0eTVyU3BtVG04WjVIVUZqOXEvT2xmdTV5WDFQCmdDZHUyb2ViN3BJWE52QkppQ1M1NisvTTJwK1k4bUFaQjdwSnlIMkNmeEFoS2trMUtJcWtNZ2dRM0Y4SXdISCsKRXAzYkpoT1MxbmlNV2ZTVUVOS1A0ZTFONkdqQitzekNEbWRvVlppTXNGQWVPd1RZaHlpSkl3N3c2YTRpbTVnSQp2TEgwekU1bE9SRFpjSUVaeXhVUHpxZGhEMmpERnIxQkVJZFBEdHBKc3NOOHFINmU5YjM3b1FJREFRQUJvMkV3Clh6QU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkVFTWdoNFlZQVdkVytTREh3S1dqWWxlbHRUagpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFMYVo3ZlF6VlpSVUFtWGRuVGU4TVRxWjRVZkJia2s4R2pxaVgwCmJ4ZjNxUkJ0RjM4K3RidlJiM2tjclVXK2pTS0M0SUpHaG5jZnlIS084YXppb3lCcW5zVXRVK1pWc3JMRVFleFkKeENlSkFPd2l5cFNob1E3eksyTmozRmVRay9Iak9NSlU4djBGNHR0Smd2SmNwY3BGQU5MU0g1Mks1Q2xhM0FHawpsaHBXcHF1aVpKV2dOOXdITjBLc0ZyVEZUb2thTHk2Ukl6RklyL1c5aDJuM3dMaU41VEJZZlV0QmFqMEhUcFhhCkVLNEU0WVhrTnRVdHJvUFBROWVKcytHbmF3RUp1N1Q2SEhtSGVoQ0xSQ1ZjWS9DdnRIbVZ3WThIN3Q4bDh4Q1UKRkxEYVZiYWNUeVIyRmROdjZ6RTVreG16TGZaWlplZVE2cVFOaEZTb0xITU9XWlF3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
    failurePolicy: Ignore
