---
# Source: kubescape-operator/templates/node-agent/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-agent
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: node-agent
    tier: ks-control-plane
    kubescape.io/ignore: "true"
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "namespaces", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["applicationprofiles", "networkneighborhoods", "seccompprofiles"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["containerprofiles", "sbomsyfts"]
  verbs: ["create", "get", "update", "watch", "list", "patch"]
- apiGroups: ["kubescape.io"]
  resources: ["runtimerulealertbindings"]
  verbs: ["list", "watch"]
- apiGroups: ["kubescape.io"]
  resources: ["operatorcommands"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["kubescape.io"]
  resources: ["operatorcommands/status"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "get"]
- apiGroups: ["kubescape.io"]
  resources: ["rules"]
  verbs: ["list", "watch"]
