---
# Source: kubescape-operator/templates/node-agent/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-agent
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: node-agent
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
data:
  config.json: |
    {
        "applicationProfileServiceEnabled": true,
        "backendStorageEnabled": false,
        "prometheusExporterEnabled": false,
        "runtimeDetectionEnabled": false,
        "httpDetectionEnabled": false,
        "networkServiceEnabled": true,
        "malwareDetectionEnabled": false,
        "hostMalwareSensorEnabled": false,
        "hostNetworkSensorEnabled": false,
        "nodeProfileServiceEnabled": false,
        "networkStreamingEnabled": false,
        "maxImageSize": 5.36870912e+09,
        "maxSBOMSize": 2.097152e+07,
        "sbomGenerationEnabled": true,
        "enableEmbeddedSBOMs": true,
        "seccompServiceEnabled": true,
        "initialDelay": "2m",
        "updateDataPeriod": "10m",
        "nodeProfileInterval": "10m",
        "networkStreamingInterval": "2m",
        "maxSniffingTimePerContainer": "24h",
        "excludeNamespaces": "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public",
        "excludeLabels":null,
        "exporters": {
          "alertManagerExporterUrls":[],
          "stdoutExporter":true,
          "syslogExporterURL": ""
        },
        "excludeJsonPaths":null,
        "ruleCooldown": {
            "ruleCooldownDuration": "1h",
            "ruleCooldownAfterCount": 1,
            "ruleCooldownOnProfileFailure": true,
            "ruleCooldownMaxSize": 20000
        }
    }
