---
# Source: kubescape-operator/templates/node-agent/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.40.4
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/version: "1.40.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: node-agent
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubescape-operator
      app.kubernetes.io/instance: kubescape
      app.kubernetes.io/component: node-agent
  template:
    metadata:
      annotations:
        
        checksum/node-agent-config: 1288a2ca115b510e038013f77fbadc97ecce46ff6d47d1cd5b40792d621f0505
        checksum/cloud-secret: 192498af36fa8b505f01b472407fcc09b948e1259f80663d34f3f3885cdf0d25
        checksum/cloud-config: 600aef8c19f11f50c49aa077b2bf72fb33d4e6e6594e88f0e70f2e5cb812b459
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        helm.sh/chart: kubescape-operator-1.40.4
        app.kubernetes.io/name: kubescape-operator
        app.kubernetes.io/instance: kubescape
        app.kubernetes.io/component: node-agent
        app.kubernetes.io/version: "1.40.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kubescape
        app: node-agent
        tier: ks-control-plane
        kubescape.io/ignore: "true"
        kubescape.io/tier: "core"
    spec:
      securityContext:
        appArmorProfile:
          type: Unconfined
      priorityClassName: kubescape-critical
      serviceAccountName: node-agent
      automountServiceAccountToken: true
      hostPID: true
      volumes:
      
      - hostPath:
          path: /
        name: host
      - hostPath:
          path: /var/lib/kubelet
        name: kubeletdir
      - hostPath:
          path: /run
        name: run
      - hostPath:
          path: /var
        name: var
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroup
      - hostPath:
          path: /lib/modules
        name: modules
      - hostPath:
          path: /sys/fs/bpf
        name: bpffs
      - hostPath:
          path: /sys/kernel/debug
        name: debugfs
      - hostPath:
          path: /boot
        name: boot
      - emptyDir: null
        name: data
      - emptyDir: null
        name: profiles
      - hostPath:
          path: /
          type: Directory
        name: host-filesystem
      - name: cloud-secret
        secret:
          secretName: cloud-secret
      - name: ks-cloud-config
        configMap:
          name: ks-cloud-config
          items:
            - key: "clusterData"
              path: "clusterData.json"
      - name: config
        configMap:
          name: node-agent
          items:
            - key: "config.json"
              path: "config.json"
      containers:
      
      
      
      - name: node-agent
        image: "quay.io/kubescape/node-agent:v0.3.219"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /livez
            port: 7888
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 7888
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /readyz
            port: 7888
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 1
        resources:
          
          limits:
            cpu: 500m
            memory: 1400Mi
          requests:
            cpu: 100m
            memory: 180Mi
        env:
          
          - name: GOMEMLIMIT
            value: "1120MiB"
          - name: HOST_ROOT
            value: "/host"
          - name: KS_LOGGER_LEVEL
            value: "info"
          - name: KS_LOGGER_NAME
            value: "zap"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBELET_ROOT
            value: "/var/lib/kubelet"
          - name: AGENT_VERSION
            value: "v0.3.219"
          - name: NodeName
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          privileged: false
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_PTRACE
              - NET_ADMIN
              - SYSLOG
              - SYS_RESOURCE
              - IPC_LOCK
              - NET_RAW
          seLinuxOptions:
            type: spc_t
        volumeMounts:
          
          - mountPath: /host
            name: host
            readOnly: true
          - mountPath: /var/lib/kubelet
            name: kubeletdir
          - mountPath: /run
            name: run
          - mountPath: /var
            name: var
            readOnly: true
          - mountPath: /lib/modules
            name: modules
            readOnly: true
          - mountPath: /sys/kernel/debug
            name: debugfs
          - mountPath: /sys/fs/cgroup
            name: cgroup
            readOnly: true
          - mountPath: /sys/fs/bpf
            name: bpffs
          - mountPath: /data
            name: data
          - mountPath: /profiles
            name: profiles
          - mountPath: /boot
            name: boot
            readOnly: true
          - name: cloud-secret
            mountPath: /etc/credentials
            readOnly: true
          - name: ks-cloud-config
            mountPath: /etc/config/clusterData.json
            readOnly: true
            subPath: "clusterData.json"
          - name: config
            mountPath: /etc/config/config.json
            readOnly: true
            subPath: "config.json"
      nodeSelector:
      
        kubernetes.io/os: linux
      affinity:
      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      tolerations:

