---
# Source: kubescape-operator/templates/node-agent/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-agent
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: node-agent
    tier: ks-control-plane
    kubescape.io/ignore: "true"
