---
# Source: kubescape-operator/templates/node-agent/servicemonitor.yaml
# If prometheus enabled, add prometheus exporter
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: runtime-monitor
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: runtime-monitor
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: runtime-monitor
    tier: ks-control-plane
    kubescape.io/ignore: "true"
spec:
  namespaceSelector:
    matchNames:
      -  kubescape
  selector:
    matchLabels:
      app.kubernetes.io/name: kubescape-operator
      app.kubernetes.io/instance: kubescape
      app.kubernetes.io/component: node-agent
  endpoints:
  - port: prometheus
    path: /metrics
    scheme: http
    interval: 30s
    scrapeTimeout: 15s
