crds:
  # -- Whether to install CRDs for monitoring.
  create: true

## Various Alloy settings. For backwards compatibility with the grafana-agent
## chart, this field may also be called "agent". Naming this field "agent" is
## deprecated and will be removed in a future release.
alloy:
  configMap:
    # -- Create a new ConfigMap for the config file.
    create: true

    content: |
      prometheus.exporter.unix "local_system" {
      }
      
      prometheus.scrape "scrape_metrics" {
        targets = [
          "prometheus.exporter.unix.local_system.targets",
          "trivy-operator.trivy-system.svc.cluster.local:80",
          "spegal.spegal-system.svc.cluster.local:9090",
          "kubelet-serving-cert-approver.kubelet-serving-cert-approver.svc.cluster.local:9090",
        ]
        forward_to      = [prometheus.relabel.filter_metrics.receiver]
        scrape_interval = "10s"
      }

      //prometheus.relabel "filter_metrics" {
      //  rule {
      //    action        = "drop"
      //    source_labels = ["env"]
      //    regex         = "dev"
      //  }
      //forward_to = [prometheus.remote_write.metrics_service.receiver]
      //}

      prometheus.remote_write "metrics_service" {
          endpoint {
              url = "http://prometheus-server.monitoring.svc.cluster.local/api/v1/write"
          }
      }

      logging {
        level  = "info"
        format = "logfmt"
      }
      
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      discovery.kubernetes "nodes" {
        role = "node"
      }
      
      discovery.kubernetes "services" {
        role = "service"
      }
      
      discovery.kubernetes "endpoints" {
        role = "endpoints"
      }
      
      discovery.kubernetes "endpointslices" {
        role = "endpointslice"
      }
      
      discovery.kubernetes "ingresses" {
        role = "ingress"
      }

      loki.write "default" {
        endpoint {
          url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }

      loki.source.file "example" {
        // Collect logs from the default listen address.
        targets = [
          {__path__ = "/tmp/foo.txt", "color" = "pink"},
          {__path__ = "/tmp/bar.txt", "color" = "blue"},
          {__path__ = "/tmp/baz.txt", "color" = "grey"},
        ]

        forward_to = [loki.write.default.receiver]
      }

      // discovery.kubernetes allows you to find scrape targets from Kubernetes resources.
      // It watches cluster state and ensures targets are continually synced with what is currently running in your cluster.
      discovery.kubernetes "pod" {
        role = "pod"
        // Restrict to pods on the node to reduce cpu & memory usage
        selectors {
          role = "pod"
          field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
        }
      }

      // discovery.relabel rewrites the label set of the input targets by applying one or more relabeling rules.
      // If no rules are defined, then the input targets are exported as-is.
      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pod.targets

        // Label creation - "namespace" field from "__meta_kubernetes_namespace"
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "namespace"
        }

        // Label creation - "pod" field from "__meta_kubernetes_pod_name"
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action = "replace"
          target_label = "pod"
        }

        // Label creation - "container" field from "__meta_kubernetes_pod_container_name"
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "container"
        }

        // Label creation -  "app" field from "__meta_kubernetes_pod_label_app_kubernetes_io_name"
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          action = "replace"
          target_label = "app"
        }

        // Label creation -  "job" field from "__meta_kubernetes_namespace" and "__meta_kubernetes_pod_container_name"
        // Concatenate values __meta_kubernetes_namespace/__meta_kubernetes_pod_container_name
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "job"
          separator = "/"
          replacement = "$1"
        }

        // Label creation - "__path__" field from "__meta_kubernetes_pod_uid" and "__meta_kubernetes_pod_container_name"
        // Concatenate values __meta_kubernetes_pod_uid/__meta_kubernetes_pod_container_name.log
        rule {
          source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "__path__"
          separator = "/"
          replacement = "/var/log/pods/*$1/*.log"
        }

        // Label creation -  "container_runtime" field from "__meta_kubernetes_pod_container_id"
        rule {
          source_labels = ["__meta_kubernetes_pod_container_id"]
          action = "replace"
          target_label = "container_runtime"
          regex = "^(\\S+):\\/\\/.+$"
          replacement = "$1"
        }
      }

      // loki.source.kubernetes tails logs from Kubernetes containers using the Kubernetes API.
      loki.source.kubernetes "pod_logs" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.process.pod_logs.receiver]
      }

      // loki.process receives log entries from other Loki components, applies one or more processing stages,
      // and forwards the results to the list of receivers in the component's arguments.
      loki.process "pod_logs" {
        stage.static_labels {
            values = {
              cluster = sys.env("CLUSTER"),
            }
        }

        forward_to = [loki.write.default.receiver]
      }

  clustering:
    # -- Deploy Alloy in a cluster to allow for load distribution.
    enabled: false

  mounts:
    # -- Mount /var/log from the host into the container for log collection.
    varlog: true
    # -- Mount /var/lib/docker/containers from the host into the container for log
    # collection.
    dockercontainers: true

serviceAccount:
  # -- Whether to create a service account for the Grafana Alloy deployment.
  create: true
  # Whether the Alloy pod should automatically mount the service account token.
  automountServiceAccountToken: true

# Options for the extra controller used for config reloading.
configReloader:
  # -- Enables automatically reloading when the Alloy config changes.
  enabled: true

controller:
  # -- Type of controller to use for deploying Grafana Alloy in the cluster.
  # Must be one of 'daemonset', 'deployment', or 'statefulset'.
  type: 'daemonset'

  # -- Number of pods to deploy. Ignored when controller.type is 'daemonset'.
  replicas: 1

  # -- Whether to enable automatic deletion of stale PVCs due to a scale down operation, when controller.type is 'statefulset'.
  enableStatefulSetAutoDeletePVC: true

  autoscaling:
    # -- Creates a HorizontalPodAutoscaler for controller type deployment.
    # Deprecated: Please use controller.autoscaling.horizontal instead
    enabled: false

  # -- Affinity configuration for pods.
  affinity: {}

networkPolicy:
  enabled: false

service:
  # -- Creates a Service for the controller's pods.
  enabled: true
  # -- Service type
  type: ClusterIP
  # -- NodePort port. Only takes effect when `service.type: NodePort`
  nodePort: 31128
  # -- Cluster IP, can be set to None, empty "" or an IP address
  clusterIP: ''
  # -- Value for internal traffic policy. 'Cluster' or 'Local'
  internalTrafficPolicy: Cluster
  annotations: {}
    # cloud.google.com/load-balancer-type: Internal

serviceMonitor:
  enabled: false

ingress:
  # -- Enables ingress for Alloy (Faro port)
  enabled: false
