---
# Source: kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubevuln-scheduler
  namespace: kubescape
  annotations:
    
  labels:
    helm.sh/chart: kubescape-operator-1.30.0
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: kubevuln-scheduler
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: kubevuln-scheduler
    tier: ks-control-plane
    kubescape.io/ignore: "true"
    armo.tier: "vuln-scan"
    kubescape.io/tier: "core"
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            
          labels:
            helm.sh/chart: kubescape-operator-1.30.0
            app.kubernetes.io/name: kubescape-operator
            app.kubernetes.io/instance: kubescape
            app.kubernetes.io/component: kubevuln-scheduler
            app.kubernetes.io/version: "1.30.0"
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/part-of: kubescape
            app: kubevuln-scheduler
            tier: ks-control-plane
            kubescape.io/ignore: "true"
            armo.tier: "vuln-scan"
            kubescape.io/tier: "core"
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: kubevuln-scheduler
            image: "quay.io/kubescape/http-request:v0.2.16"
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 10m
                memory: 20Mi
              requests:
                cpu: 1m
                memory: 10Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 100
            args:
              - -method=post
              - -scheme=http
              - -host=operator:4002
              - -path=v1/triggerAction
              - -headers=Content-Type:application/json
              - -path-body=/home/ks/request-body.json
            volumeMounts:
              - name: kubevuln-scheduler
                mountPath: /home/ks/request-body.json
                subPath: request-body.json
                readOnly: true
          restartPolicy: Never
          serviceAccountName: kubevuln
          automountServiceAccountToken: false
          nodeSelector:
            kubernetes.io/os: linux
          affinity:
          tolerations:
          volumes:
          - name: kubevuln-scheduler
            configMap:
              name: kubevuln-scheduler
